apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-qgis
  namespace: {{ .Release.Namespace | default "qgis" }}
  labels:
    app.kubernetes.io/name: qgis
    app.kubernetes.io/instance: {{ .Release.Name }}
