apiVersion: v1
kind: Service
metadata:
  name: qgis
  namespace: {{ .Release.Namespace | default "qgis" }}
  labels:
    app.kubernetes.io/name: qgis
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8888
      protocol: TCP
{{- if .Values.mcp.enabled }}
    - name: mcp-http
      port: {{ .Values.service.mcp.port }}
      targetPort: mcp-http
      protocol: TCP
{{- end }}
  selector:
    app.kubernetes.io/name: qgis
    app.kubernetes.io/instance: {{ .Release.Name }}
